@TaskManagerWEB.Api_HostAddress = https://localhost:7109

GET {{TaskManagerWEB.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TaskManagerWEB.Api_HostAddress}}/api/taskitem

###

POST {{TaskManagerWEB.Api_HostAddress}}/api/taskitem
Content-Type: application/json

"string"

###
